### PR TITLE
ignore deprecated in .h files where it happends for cocoapods integra…

### PR DESCRIPTION
**Pull request by pchien**
…tions that aren't using surveys

### CODE REVIEW

**Comment by nickvelloff** [comment]
@pchien can we light this candle? 🙇

**Comment by yarneo** [comment]
LGTM

**Comment by itsallmememe** [comment]
I've updated to the latest MixPanel (3.0.9) and I'm still getting these errors - Xcode 8.2.1

**Comment by pchien** [comment]
Interesting. It worked for me in the test apps that we use. It's possible Xcode is caching things so try cleaning and deleting DerivedData? Let me know if that helps. If not, can I know what method of integration you're using or maybe if you can reproduce it in a small test/demo app?

**Comment by dstarke** [comment]
I'm still seeing a large number of warnings about deprecations related to surveys when building 3.0.9 via Carthage.

**Pull request merged**
