### PR TITLE
fix import using angles instead of quotes

### PR DESCRIPTION
**Pull request by zihejia**
https://github.com/mixpanel/mixpanel-iphone/issues/852

### CODE REVIEW

**Comment by marceloqueiroz** [comment]
@zihejia Do you mind creating a new release after this fix?

**Comment by zihejia** [comment]
yes, it will be in the next release.

**Comment by marceloqueiroz** [comment]
Great, is there an expected date for it?

--
Marcelo Queiroz

**Comment by zihejia** [comment]
The next version will combine several other issues together but I don't have an ETA for now. Is it possible for you to point to the master as a workaround for now? since this PR has already been merged.

**Comment by marceloqueiroz** [comment]
I would be hard to push the use of it pointing to master. 

--
Marcelo Queiroz

**Pull request merged**
