### PR TITLE
Extraneous semicolon

### PR DESCRIPTION
**Pull request by shortstuffsushi**

### CODE REVIEW

**Comment by Quuxplusone** [comment]
`MPWebSocket.m` has at least a couple, too. Could you `git grep '};'` the whole repo? (Blocks and NSDictionary literals make for a lot of false positives, but there are still many true positives.)

**Comment by shortstuffsushi** [comment]
Updated with the other ones I found.

**Comment by shortstuffsushi** [comment]
@Quuxplusone poke, any thoughts on this?

**Comment by alex-hofsteede** [comment]
Thanks @shortstuffsushi

**Comment by shortstuffsushi** [comment]
Sure :)

**Comment by shortstuffsushi** [comment]
Sure :)

**Pull request merged**
