### PR TITLE
remove duplicate assets

### PR DESCRIPTION
**Pull request by olarivain**
Hey,

This PR removes an asset that's duplicated (MPCloseBtn). The asset is present on both the FS and in the image catalog. The resource spec matches *.png, so that asset is included twice.
If you're using static libraries, this isn't an issue since cocoa pods only one image will end up in the resources, but if you start using frameworks, this causes Xcode to generate a warning.

Since the image is in present in the asset catalog, along with some others, I took the liberty the "standalone" version.

### CODE REVIEW

**Comment by siemensikkema** [comment]
+1

**Comment by oldtinroof** [comment]
+1 Anyone using MP in Rubymotion is blocked by this.

**Comment by raylillywhite** [comment]
:+1: Please merge

**Comment by matias-pequeno** [comment]
:+1: Please, merge.

**Comment by matias-pequeno** [comment]
We were able to silence the warning, if you're fetching Mixpanel using Cocoapods you can add a `pre_install` hook and delete the duplicated files before the Pods project file is generated:

```
pre_install do |installer_representation|
  # Temporary until Mixpanel merges https://github.com/mixpanel/mixpanel-iphone/pull/245
  FileUtils.remove(Dir.pwd + '/Pods/Mixpanel/Mixpanel/MPCloseBtn.png')
  FileUtils.remove(Dir.pwd + '/Pods/Mixpanel/Mixpanel/MPCloseBtn@2x.png')
end
```

**Comment by samgreen** [comment]
This is resolved in v2.8.2, so I'm closing this PR. Please open an issue if you're still having trouble.

**Pull request closed without merging**
