### PR TITLE
Update MPTweakInline to handle multiple dynamically loaded images.

### PR DESCRIPTION
**Pull request by samgreen**

### CODE REVIEW

**Comment by projectAZB** [comment]
Hey Sam, my team and I were experiencing the exact problem detailed in #346, found your solution, replaced the contents of Mixpanel/MPTweakInline.m with your fix, and everything worked perfectly. I was wondering why this hasn't been merged into the SDK yet, and what sort of errors you could foresee going forward with your unmerged fix integrated into the project.

**Comment by samgreen** [comment]
Hi @projectAZB, glad that the fix in #364 works for you. We originally wrote the fix as a means to allow tweaks in Swift. Unfortunately adding tweaks to Swift ended up being a lot more tricky than we initially estimated. That's why the original PR was never merged and released.

I can see how the PR would also resolve the original issue and should be merged in for the next release ASAP. I don't foresee any issues in using this code moving forward. I believe it to be more hardened and more reliable as it will iterate over all of the loaded images in memory. I've tagged that PR for the next release and I'll update you when it is merged.

**Comment by projectAZB** [comment]
Perfect, this was a huge help, thanks for your response!

**Comment by rdbayer** [comment]
I'm using build 2.9.2, but I'm still getting this error when I try to use MPTweakValue():

```'MPTweakValue' (aka 'AnyObject') cannot be constructed because it has no accessible initializers.```

@samgreen Is MPTweakValue("x", 5) meant to work now in Swift, or is there a workaround I'm meant to use?

**Pull request merged**
