### PR TITLE
Require Only App-Extension Safe API for the Carthage project.

### PR DESCRIPTION
**Pull request by samgreen**

### CODE REVIEW

**Comment by poolqf** [comment]
:+1: !!!

**Comment by samgreen** [comment]
Unfortunately there is an issue with this PR. Looks like we need a way to define this build setting based on the status of `MIXPANEL_APP_EXTENSION`

screen shot 2016-01-20 at 1 26 22 pm

**Comment by poolqf** [comment]
Waiting for it :smile:

**Comment by samgreen** [comment]
Hey @poolqf sorry for the delay on this. It is resolved in 445.

**Pull request closed without merging**
