### PR TITLE
Added MixpanelExceptionHandler.

### PR DESCRIPTION
**Pull request by samgreen**

### CODE REVIEW

**Comment by alex-hofsteede** [comment]
Can we create a unit test for this functionality? or is there no real way to assert something after forcing a crash?

**Comment by idStar** [comment]
@samgreen Not sure if more is coming in this branch as I see your pull request. I just tested this branch and events are still jammed after a crash. I'll keep testing as you have updates.

events_are_still_jammed

**Comment by idStar** [comment]
@samgreen I've noticed the SDK when from version `2.8.3` to `2.9.0`, but there's some serious issues in Milestone 2.8.4 (notably this one) that have had no movement in months. What's the plan? 

This is a serious bug and limitation of the SDK as it stands right now.

**Comment by idStar** [comment]
It looks like Milestone 2.9.1 has been released (https://github.com/mixpanel/mixpanel-iphone/releases/tag/v2.9.1) but this issue didn't make it in. It's been open since July 2015 and is quite serious. Can someone advise on what the realistic roadmap for this is?

**Comment by samgreen** [comment]
Hey @idStar so sorry for the churn on this. We've been super distracted here, but we're taking another look and hoped to get this resolved in Jan.

**Comment by idStar** [comment]
@samgreen Per my comment in Issue #303 [here](https://github.com/mixpanel/mixpanel-iphone/issues/303#issuecomment-167680898), would it be possible to rebase this branch from master, so that modern Carthage support is available to it? 

I want to try this branch in my own (real) app, but it's not coming in cleanly with Carthage, as I believe this branch predates some more robust Carthage support. Thanks.

**Comment by idStar** [comment]
Following up for documentation purposes, the problem I posted above is no longer an issue for me, as tested with the current code in `master` of this repo, and me having switched to eagerly initializing my `Mixpanel` sharedInstance, instead of lazily (not sure why that would matter, but it helped).

Full details in ticket #303: https://github.com/mixpanel/mixpanel-iphone/issues/303#issuecomment-168109441

**Comment by samgreen** [comment]
Merging this for next release.

**Pull request merged**
