### PR TITLE
Fix warnings from XCode 6.3 iOS 8.3 for overriding properties

### PR DESCRIPTION
**Pull request by welshm**
"Auto property synthesis will not synthesize property 'view'; it will be implemented by its superclass, use @dynamic to acknowledge intention"

### CODE REVIEW

**Comment by anderscarling** [comment]
:+1:

**Comment by honkfestival** [comment]
:+1:

**Comment by soleares** [comment]
:+1:

**Comment by DAKarp** [comment]
:+1:

**Comment by welshm** [comment]
@alex-hofsteede Since you've merged a similar change, shall I drop this? I think the comments are helpful though to indicate why dynamic is being declared.

**Comment by alex-hofsteede** [comment]
@welshm yeah the comments are useful, can you rebase on current master, and I'll merge this.

**Comment by welshm** [comment]
@alex-hofsteede Rebased to current master and updated. Thanks!

**Pull request merged**
