### PR TITLE
Synchronize flushQueue using each queue as the mutex token

### PR DESCRIPTION
**Pull request by samgreen**
Ensure the flushQueue method synchronizes on the queue parameter that is passed in. This should prevent issues with multi-threaded code that attempts the mutate the underlying data structures.

### CODE REVIEW

**Comment by samgreen** [comment]
This should resolve #276.

**Comment by alex-hofsteede** [comment]
Can I get a rationale for this change? 

The way the curernt model works, we should always be mutating these lists on the serial queue, so race conditions should not be a problem. If there are other threads modifying the underlying data structures in a non safe manner, then we should fix that. If we can point to a specific case where it truly is best to be modifying the underlying data from another thread, then we can consider adding synchronized.

The main point is that if the code is doing something bad. I'd rather just stop doing the bad thing instead of adding another safety net.

**Comment by samgreen** [comment]
My rationale for this change is to be more defensive in protecting the call to `flush`. I protected this code in response to #276. As it stands now, if users of our library call `flush` on a background thread, and our flush timer calls it on the main thread, we will have a race condition as both threads attempt to mutate the queues.

**Comment by samgreen** [comment]
To be clear, this change is not due to any of the code we've written and is to protect consumers of our library. It may make more sense as an assert to ensure its only called from the main thread. In which case we just need to document to users this method is NOT thread safe.

**Comment by alex-hofsteede** [comment]
Everything inside `[mixpanel flush]` is a block which is added to the serial queue. Access to these structures should already be 'serialized' by virtue of the serial queue. Obviously we're breaking that somewhere, and we need to fix that, but adding another layer of of serialization safety net doesn't fix that so much as cover up a bug that we have somewhere.

**Comment by samgreen** [comment]
Ah I missed the higher level call. Got it.

**Pull request closed without merging**
